# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=1000
bindkey -e

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "~/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

# enable bash completion compatibility mode
autoload bashcompinit
bashcompinit

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-autosuggestions"
zplug "k4rthik/git-cal", as:command

# set the priority when loading
# e.g., zsh-syntax-highlighting must be loaded
# after executing compinit command and sourcing other plugins
# (If the defer tag is given 2 or above, run after compinit command)
zplug "zsh-users/zsh-syntax-highlighting", defer:2

# GEOMETRY_PROMPT_PLUGINS=(virtualenv exec_time git hg node)
# zplug "frmendes/geometry", as:theme
zplug 'simnalamburt/shellder', as:theme
# zplug "dracula/zsh", as:theme

# fix garish, unreadable green and yellow node segment colours
# POWERLEVEL9K_NODE_VERSION_BACKGROUND="red"
# POWERLEVEL9K_NODE_VERSION_FOREGROUND="white"
# zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time $TOOL_VERSION)
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
# POWERLEVEL9K_SHORTEN_DELIMITER=""
# POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

zplug "rimraf/k"
zplug "rupa/z", use:z.sh
zplug "Russell91/sshrc", from:github, as:command, use:"sshrc"

# completions

zplug "zplug/zplug", hook-build: "zplug --self-manage"

# install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

# source plugins and add commands to $PATH
zplug load

# see output of `brew info nvm` for details
export NVM_DIR="$HOME/.nvm"
source "/usr/local/opt/nvm/nvm.sh"

export GOPATH="$HOME/go"
export PATH="/usr/local/sbin:$HOME/.rbenv/bin:$HOME/.local/bin:$PATH"

if [[ `uname` == 'Darwin' ]] then
  # find a way to install them by zplug
  # https://github.com/littleq0903/gcloud-zsh-completion
  # others: https://github.com/unixorn/awesome-zsh-plugins#even-more-completions
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# load custom functions & aliases
source ~/.helpers/index
